
## Harness application will be installed in this namespace in the given cluster
kubernetesClusterNamespace: harness

accounts:
  accountName: Demo-Account
  companyName: Demo-Company
  adminEmail: admin@harness.io

privatedockerrepo:
  docker_registry_url:
  docker_registry_username:
  docker_registry_password:
  docker_reg_auths_url:
  docker_registry_email:

inframapping:
  lbUrl: http://127.0.0.1
  lbIpAddress: 127.0.0.1
