apiVersion: v1
kind: ConfigMap
metadata:
  name: verification-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  DEPLOY_MODE: KUBERNETES_ONPREM
  LOGGING_LEVEL: {{ .Values.appLogInfo | quote }}
  MANAGER_URL: http://harness-manager:9090/api/
  MEMORY: {{ .Values.java.memory | quote }}
  VERIFICATION_PORT: {{ .Values.service.port | quote }}
  VERSION: 1.0.77622
  VERIFICATION_SERVICE_SECRET: 59MR5RlVARcdH7zb7pNx6GzqiglBmXR8
  LOCK_CONFIG_REDIS_URL: { { include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) } }
  LOCK_CONFIG_REDIS_SENTINELS: { { include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) } }
  LOCK_CONFIG_SENTINEL_MASTER_NAME: "harness-redis"
  LOCK_CONFIG_USE_SENTINEL: { { .Values.global.database.redis.installed | quote } }
  {{ if .Values.global.mongoSSL }}
  MONGO_SSL_CONFIG: "true"
  MONGO_SSL_CA_TRUST_STORE_PATH: /opt/harness/keystore.jks
  MONGO_SSL_CA_TRUST_STORE_PASSWORD: password
  {{ end }}
  {{ include "harnesscommon.harnessfunctions.java17flags" (dict "context" $) | nindent 2 }}
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
