apiVersion: v1
kind: ConfigMap
metadata:
  name: cv-nextgen
  namespace: {{ .Release.Namespace }}
data:
  DEPLOY_MODE: {{ .Values.config.DEPLOY_MODE }}
  ENV: {{ .Values.config.ENV }}
  LOGGING_LEVEL: {{ .Values.appLogLevel }}
  MANAGER_URL: http://harness-manager.{{ .Release.Namespace }}.svc.cluster.local:9090/
  NG_MANAGER_URL: http://ng-manager.{{ .Release.Namespace }}.svc.cluster.local:7090/
  MEMORY: {{ .Values.java.memory | quote }}
  STACK_DRIVER_LOGGING_ENABLED: {{ .Values.global.stackDriverLoggingEnabled | quote }}
  VERIFICATION_PORT: {{ .Values.config.VERIFICATION_PORT | quote }}
  VERIFICATION_SERVICE_SECRET: {{ .Values.config.VERIFICATION_SERVICE_SECRET | quote }}
  NOTIFICATION_BASE_URL: http://platform-service.{{ .Release.Namespace }}.svc.cluster.local:9005/api/
  SHOULD_CONFIGURE_WITH_NOTIFICATION: {{ .Values.config.SHOULD_CONFIGURE_WITH_NOTIFICATION | quote }}
  PORTAL_URL: {{ .Values.global.loadbalancerURL }}
  MANAGER_CLIENT_BASEURL: http://harness-manager.{{ .Release.Namespace }}.svc.cluster.local:9090/
  ET_SERVICE_BASE_URL: http://et-service.{{ .Release.Namespace }}.svc.cluster.local:9191/api/
  EVENTS_FRAMEWORK_REDIS_URL: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) }}
  EVENTS_FRAMEWORK_USE_SENTINEL: {{ .Values.global.database.redis.installed  | quote }}
  EVENTS_FRAMEWORK_SENTINEL_MASTER_NAME: 'harness-redis'
  EVENTS_FRAMEWORK_REDIS_SENTINELS: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) }}
  SHOULD_CONFIGURE_WITH_PMS: "true"
  LOCK_CONFIG_REDIS_SENTINELS: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) }}
  LOCK_CONFIG_SENTINEL_MASTER_NAME: harness-redis
  LOCK_CONFIG_USE_SENTINEL:  {{ .Values.global.database.redis.installed  | quote }}
  PMS_TARGET: pipeline-service:12011
  PMS_AUTHORITY: pipeline-service:12011
  GRPC_SERVER_PORT: "9979"
  CACHE_CONFIG_REDIS_URL: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) }}
  CACHE_BACKEND: "REDIS"
  CACHE_CONFIG_REDIS_SENTINELS: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) }}
  CACHE_CONFIG_SENTINEL_MASTER_NAME: "harness-redis"
  CACHE_CONFIG_USE_SENTINEL: {{ .Values.global.database.redis.installed  | quote }}
  LOCK_CONFIG_REDIS_URL: {{ include "harnesscommon.dbconnection.redisConnection" (dict "context" .Values.global.database.redis) }}
  MOCK_ACCESS_CONTROL_SERVICE: "false"
  ACCESS_CONTROL_BASE_URL:  http://access-control.{{ .Release.Namespace }}.svc.cluster.local:9006/api/
  ACCESS_CONTROL_ENABLED: {{ .Values.config.ACCESS_CONTROL_ENABLED | quote }}
  ENABLE_DASHBOARD_TIMESCALE: "true"
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}