config:
  ignore:
    - "README.md"
    - ".ticonfig.yaml"
    - "jira-projects.txt"
    - "jdk11test.txt"
    - "**/*.go"
    - "**/*.md"
    - "**/Dockerfile*"
    - "scripts/jenkins/**/*"
    - "scripts/terraform/**/*"
    - "on-prem/**/*"
    - "docs/**/*"
    - "licenses/**/*"
    - "img/**/*"
    - "dockerization/**/*"
    - "scripts/jenkins/*"
    - "product/**/*"
    - "commons/**/*"
    - "**/*.hash"
    - "toolset/git-hooks/**/*"
    - "build.properties"