config:
  ignore:
    - "README.md"
    - ".ticonfig.yaml"
    - "jira-projects.txt"
    - "jdk11test.txt"
    - "**/*.info"
    - "**/*.log"
    - "**/*.pem"
    - "**/*.cer"
    - "**/*.py"
    - "**/*.go"
    - "**/*.md"
    - "**/Dockerfile*"
    - "scripts/jenkins/**/*"
    - "scripts/terraform/**/*"
    - "on-prem/**/*"
    - "charts/**/*"
    - "chart/**/*"
    - "manifest.yaml"
    - "docs/**/*"
    - "licenses/**/*"
    - "img/**/*"
    - "docker-files/**/*"
    - "dockerization/**/*"
    - "queue-service/**/*"
    - "scripts/jenkins/*"
    - "product/**/*"
    - "commons/**/*"
    - "**/*.hash"
    - "toolset/git-hooks/**/*"
    - "**/build.properties"
    - "332-ci-manager/config/ci-manager-config.yml"
    - "332-ci-manager/build/container/scripts/replace_configs.sh"
