config:
  ignore:
    - "README.md"
    - ".ticonfig.yaml"
    - "**/*.go"
    - "**/Dockerfile*"
    - "**/README.md"
    - "scripts/jenkins/**/*"
    - "scripts/terraform/**/*"
    - "on-prem/**/*"
    - "dockerization/**/*"
    - "scripts/jenkins/*"
    - "product/**/*"
    - "commons/**/*"
    - "**/*.hash"
    - "toolset/git-hooks/**/*"
    - "build.properties"
