server:
  applicationConnectors:
    - type: h2
      port: 9090
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: selfsigned
      validateCerts: false
    - type: http
      port: 3457
  adminConnectors:
    - type: h2
      port: 9091
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: selfsigned
      validateCerts: false

logging:
  appenders:
    - type: console
      threshold: INFO
      target: stdout

mongo:
  host: localhost
  port: 27017
  db: wings

portal:
  url: https://localhost:8000
  allowedDomains: wings.software
  companyName: Wings Software
