server:
  applicationContextPath: /wings
  applicationConnectors:
    - type: http
      port: 9090
  adminContextPath: /admin
  adminMinThreads: 1
  adminMaxThreads: 64
  adminConnectors:
    - type: http
      port: 9091
logging:
  appenders:
    - type: console
      threshold: INFO
      target: stdout

mongo:
  host: localhost
  port: 27017
  db: wings

portal:
  url: http://192.168.1.15:9090/wings

jenkinsBuildQuerySize: 50

enableAuth: true
