managerUrl: https://localhost:9090/api/
server:
  applicationConnectors:
    - type: https
      port: 7171
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
      maxRequestHeaderSize: 100KiB
    - type: http
      port: 4457
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: https
      port: 7071
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
  requestLog:
    appenders: []

logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"

harness-mongo:
  uri: mongodb://localhost:27017/harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 50
cimanager-mongo:
  uri: mongodb://localhost:27017/harnessci
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
delegateGrpcServiceTokenSecret: "j6ErHMBlC2dn6WctNQKt0xfyo_PZuK7ls0Z4d6XCaBg"