logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false

server:
  applicationConnectors:
    - type: http
      port: 13001
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: http
      port: 13002
  requestLog:
    appenders: []
  maxThreads: 1024


debeziumConfigs:
  - isEnabled: true
<<<<<<< HEAD:951-debezium-service/config.yml
    offset.storage.file.filename: redisson-jcache.yaml
    offset.storage.topic: debezium-offsets-pipeline
=======
    offset.storage.file.filename: redis://127.0.0.1:6379
>>>>>>> parent of 6f3b123dea9... techdebt: [PIE-3190]: Debezium version upgrade (#31542):951-debezium-service-application/config.yml
    name: pipeline
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    offset.flush.interval.ms: 5000
    mongodb.hosts: localhost:27017
    mongodb.name: pmsMongo
    mongodb.user:
    mongodb.password:
    mongodb.ssl.enabled: false
    connector.class: io.debezium.connector.mongodb.MongoDbConnector
    database.include.list: pms-harness
    collection.include.list: pms-harness.planExecutionsSummary
    connect.backoff.initial.delay.ms: 1000
    connect.backoff.max.delay.ms: 10000
    connect.max.attempts: 3
    snapshot.fetch.size: 2000

eventsFramework:
  redis:
    sentinel: false
    masterName: "test"
    redisUrl: "redis://localhost:6379"
    sentinelUrls:
      - "redis://redis1:26379"
      - "redis://redis2:26379"
      - "redis://redis3:26379"
    envNamespace: ""
    readMode: MASTER
    nettyThreads: 16
    useScriptCache: true
    userName: ""
    password: ""
    sslConfig:
      enabled: false
      CATrustStorePath: "/tmp/ca_trust_store"
      CATrustStorePassword: ""

redisLockConfig:
  sentinel: false
  masterName: "test"
  redisUrl: "redis://localhost:6379"
  sentinelUrls:
    - "redis://redis1:26379"
    - "redis://redis2:26379"
    - "redis://redis3:26379"
  envNamespace: ""
  readMode: MASTER
  nettyThreads: 16
  useScriptCache: true
  userName: ""
  password: ""

distributedLockImplementation: REDIS