openapi: 3.0.0
x-stoplight:
  id: nf3qya0lfm394
info:
  title: Harness NextGen Software Delivery Platform API Reference
  version: '1.0'
  description: This is the Open Api Spec 3 for the SSCA Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
  contact:
    email: contact@harness.io
servers:
  - url: 'https://app.harness.io'
    description: Harness host URL.
paths:
  '/v1/org/{org}/project/{project}/sbom/process':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
    post:
      summary: process raw SBOM into harness usable normalized form
      operationId: process-sbom
      responses:
        '200':
          $ref: '#/components/responses/SbomProcessResponseBody'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
      description: process & inject sbom
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/SbomProcessRequestBody'
      tags:
        - sbomProcessor
      security:
        - x-api-key: []
  '/v1/org/{org}/project/{project}/sbom/enforcement':
    parameters:
      - $ref: '#/components/parameters/OrgParam'
      - $ref: '#/components/parameters/ProjectParam'
    post:
      summary: enforce normalized SBOM based on policies applied
      operationId: enforce-sbom
      responses:
        '200':
          $ref: '#/components/responses/EnforceSbomResponseBody'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
        '502':
          description: Bad Gateway
      description: enforce an sbom
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/EnforceSbomRequestBody'
      tags:
        - sbomProcessor
      security:
        - x-api-key: []
  /v1/token:
    get:
      summary: Issue a cross-service token
      tags:
        - Token
      responses:
        '200':
          $ref: '#/components/responses/TokenIssueResponseBody'
      operationId: Token#IssueToken
      x-stoplight:
        id: lfdnr4gsxm6xy
      description: Issue a cross-service token
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
      security:
        - x-api-key: []
  '/v1/org/{org}/project/{project}/orchestration/{orchestration-id}/summary':
    parameters:
      - name: org
        in: path
        required: true
        schema:
          type: string
        description: Harness Organization Id
      - in: path
        required: true
        schema:
          type: string
        description: Harness Project Id
        name: project
      - schema:
          type: string
        name: orchestration-id
        in: path
        required: true
    get:
      summary: Get Orchestration Summary
      responses:
        '200':
          $ref: '#/components/responses/OrchestrationSummaryResponseBody'
      operationId: getOrchestrationSummary
      x-stoplight:
        id: 1n9aed40nyr4e
      description: Get Orchestration Summary
      security:
        - x-api-key: []
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
      x-internal: true
      tags:
        - orchestration
  '/v1/org/{org}/project/{project}/enforcement/{enforcement-id}/summary':
    parameters:
      - name: org
        in: path
        required: true
        schema:
          type: string
        description: Harness Organization Id
      - in: path
        required: true
        schema:
          type: string
        description: Harness Project Id
        name: project
      - schema:
          type: string
        name: enforcement-id
        in: path
        required: true
    get:
      summary: Get Enforcement Summary
      responses:
        '200':
          $ref: '#/components/responses/EnforcementSummaryResponseBody'
      operationId: getEnforcementSummary
      x-stoplight:
        id: jzq85doo8tlk5
      description: Get Enforcement Summary
      security:
        - x-api-key: []
      tags:
        - enforcement
      parameters:
        - $ref: '#/components/parameters/AccountHeader'
components:
  schemas:
    Artifact:
      title: Artifact
      x-stoplight:
        id: 5aekk9m4lzej8
      type: object
      x-examples: {}
      properties:
        id:
          type: string
          description: id of the artifact
          example: 089855ea-f90e-4bea-a5c9-b5ddf85d3180
        type:
          type: string
          description: type of the artifact
          example: repo/image
        name:
          type: string
          description: name of the artifact
          example: harness/image
        tag:
          type: string
          description: tag of the artifact
          default: latest
          example: latest
        registry_url:
          type: string
          description: url of the artifact
          example: 'https://console.cloud.google.com/gcr/images/imageName'
      required:
        - name
        - registry_url
    SbomProcess:
      title: SbomProcess
      x-stoplight:
        id: y2hb3u4kauit0
      type: object
      properties:
        name:
          type: string
          description: name of the sbom
          example: SBOM_Name
        data:
          type: string
          format: byte
          description: serialised sbom data
        format:
          type: string
          description: format of the SBOM
          example: spdx-json
        url:
          type: string
          description: URL of the sbom
          example: 'https://console.google.com/storage'
      required:
        - name
        - format
    Attestation:
      title: Attestation
      x-stoplight:
        id: 3b6pbyc78i7wd
      type: object
      properties:
        is_attested:
          type: boolean
          default: false
          description: is the sbom attested or not
        url:
          type: string
          description: url of the attested file
          example: 'https://storage.googleapis.com/sbom_store_public/kmpySmUISimoRrJL6NL73w/default/SSCS_CI_Plugin_Demo/CKO_SSCA_Pipeline/Build/39/q940CvjoQj-GEInJQfWiwg/sbom'
    SbomMetadata:
      title: SbomMetadata
      x-stoplight:
        id: 3x3lrzy9yzqub
      type: object
      properties:
        format:
          type: string
          description: stage name where sbom is generated
          minLength: 3
          example: spdx-json
        tool:
          type: string
          description: name of the package
          minLength: 3
          example: synk
        pipeline_execution_id:
          type: string
          description: name of the package
          example: z940CvjoQj-GEInJQfWiwq
          minLength: 3
        sequence_id:
          type: string
          description: name of the package
          example: '1'
        pipeline_identifier:
          type: string
          description: name of the package
          example: SSCA_Pipeline
          minLength: 3
        stage_identifier:
          type: string
          description: name of the Stage
          example: Build
        step_identifier:
          type: string
          description: id of the step
          example: Orchestrate
        build_url:
          type: string
          description: BuildURL
          example: 'https://app.harness.io/ng/#/account/acc/ci/orgs/org/projects/dummyProject/pipelines/CKO_SSCA_Pipeline/executions/q940CvjoQj-GEInJQfWiwg/pipeline?storeType=INLINE'
        step_execution_id:
          type: string
          description: StepExecutionId
          example: betatest1
    SbomProcessRequestBody:
      title: SbomProcessRequestBody
      x-stoplight:
        id: 2ej147flnmxhw
      type: object
      properties:
        artifact:
          $ref: '#/components/schemas/Artifact'
        sbom_process:
          $ref: '#/components/schemas/SbomProcess'
        attestation:
          $ref: '#/components/schemas/Attestation'
        sbom_metadata:
          $ref: '#/components/schemas/SbomMetadata'
    SbomProcessResponseBody:
      title: SbomProcessResponseBody
      x-stoplight:
        id: kfjzcnavg7zfn
      type: object
      properties:
        artifact_id:
          type: string
          description: Id of created artifact
    EnforceSbomResponseBody:
      title: SbomEnforceResponseBody
      x-stoplight:
        id: 2ch2vh1kcu4yj
      type: object
      properties:
        enforcement_id:
          type: string
          description: ID of the enforcement of the SBOM
        status:
          type: string
          description: Status of the enforcement
      required:
        - enforcement_id
    EnforceSbomRequestBody:
      title: SbomEnforceRequestBody
      x-stoplight:
        id: xlwx0g2swgery
      type: object
      properties:
        enforcement_id:
          type: string
        artifact:
          $ref: '#/components/schemas/Artifact'
        policy_file_id:
          type: string
    TokenIssueResponseBody:
      title: TokenIssueResponseBody
      x-stoplight:
        id: m3cidf4usfgo5
      type: object
      x-internal: true
      properties:
        token:
          type: string
          description: Issued cross-service JWT
      required:
        - token
    TokenIssueTokenResponseBody:
      type: object
      properties:
        token:
          type: string
          x-stoplight:
            id: 62vk4wkhrtc0e
          description: Issued cross-service JWT
      required:
        - token
      title: ''
      x-internal: true
    OrchestrationSummaryResponse:
      title: OrchestrationSummary
      x-stoplight:
        id: t0sjc6cfwopbr
      type: object
      properties:
        step_execution_id:
          type: string
          x-stoplight:
            id: jftxdzy4rhm3y
        is_attested:
          x-stoplight:
            id: m82ynd4l6slp8
          type: boolean
        artifact:
          $ref: '#/components/schemas/Artifact'
        sbom:
          $ref: '#/components/schemas/SbomDetails'
    EnforcementSummaryResponse:
      title: EnforcementSummaryResponse
      x-stoplight:
        id: 76lz28i62f144
      type: object
      properties:
        artifact:
          $ref: '#/components/schemas/Artifact'
        enforcement_id:
          type: string
          x-stoplight:
            id: 1brcqnddmncyn
        allow_list_violation_count:
          type: integer
          x-stoplight:
            id: 8dtpohq70jks7
        deny_list_violation_count:
          type: integer
          x-stoplight:
            id: 9zh0hehjoqujw
        status:
          type: string
          x-stoplight:
            id: f6yugk26rrsad
      description: Enforcement Summary
    SbomDetails:
      title: SbomDetails
      x-stoplight:
        id: a0dhiojgxty14
      type: object
      description: Sbom Details
      properties:
        name:
          type: string
          x-stoplight:
            id: 3azt0nudorbsy
      required:
        - name
  parameters:
    OrgParam:
      name: org
      in: path
      required: true
      schema:
        type: string
      description: Harness Organization Id
    ProjectParam:
      in: path
      required: true
      schema:
        type: string
      description: Harness Project Id
      name: project
    AccountHeader:
      name: Harness-Account
      in: header
      required: false
      schema:
        type: string
      description: 'Identifier field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.'
  requestBodies:
    SbomProcessRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SbomProcessRequestBody'
    EnforceSbomRequestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EnforceSbomRequestBody'
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key1 is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
  responses:
    SbomProcessResponseBody:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SbomProcessResponseBody'
    EnforceSbomResponseBody:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EnforceSbomResponseBody'
    TokenIssueResponseBody:
      description: Response body for token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TokenIssueResponseBody'
    OrchestrationSummaryResponseBody:
      description: Step Execution Response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrchestrationSummaryResponse'
    EnforcementSummaryResponseBody:
      description: Enforcement Summary Response Body
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/EnforcementSummaryResponse'
tags:
  - name: sbomProcessor
