{{- if .Values.global.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "ci-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  gateways:
    {{- if .Values.global.istio.gateway.create }}
    - istio-system/public
    {{- else }}
    {{- range .Values.global.istio.virtualService.gateways }}
    - {{ . }}
    {{- end }}
    {{- end }}
  hosts:
    {{- range .Values.global.istio.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  http:
  - name: ci-manager
    match:
      - uri:
          prefix: /ng/api/
      - uri:
          prefix: /ng/api
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: ci-manager
{{ end }}