harness-mongo:
  uri: mongodb://localhost:30001/harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

events-mongo:
  uri: mongodb://localhost:30001/events
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

cdc-mongo:
  uri: mongodb://localhost:30001/change-data-capture
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

timescaledb:
  timescaledbUrl: "jdbc:postgresql://34.83.25.129:5432/harnessccmdev"
  timescaledbUsername: "harnessappdev"
  timescaledbPassword: "harnessappdev"
  connectTimeout: 10
  socketTimeout: 30
  logUnclosedConnections: false
  loggerLevel: OFF