apiVersion: v1
kind: ConfigMap
metadata:
  name: ssca-manager
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.global.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.global.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  SERVER_PORT: "8188"
  LOGGING_LEVEL: INFO
  MONGO_INDEX_MANAGER_MODE: AUTO
  NG_MANAGER_BASE_URL: http://ng-manager.{{ .Release.Namespace }}.svc.cluster.local:7090
  DEPLOY_MODE: KUBERNETES_ONPREM
  STACK_DRIVER_LOGGING_ENABLED: '{{ .Values.global.stackDriverLoggingEnabled }}'
  S3_BUCKET: {{ .Values.s3.sbomBucketName }}
  {{- if .Values.s3.endpoint }}
  S3_ENDPOINT: {{ .Values.s3.endpoint }}
  {{- else }}
  S3_ENDPOINT: 'http://minio.{{ .Release.Namespace }}.svc.cluster.local:9000'
  {{- end }}
  S3_POLICY_BUCKET: {{ .Values.s3.policyBucketName }}
  S3_REGION: {{ .Values.s3.region }}
