apiVersion: v1
kind: Secret
metadata:
  name: platform-service-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "platform-service.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- include "platform-service.generateSecrets" (dict "ctx" $) | indent 2 }}
