server:
  port: 8080
  ssl:
    enabled: true
    key-alias: scg
    key-store-password: scg1234
    key-store: classpath:scg-keystore.p12
    key-store-type: PKCS12

spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
          handshake-timeout-millis: 10000
          close-notify-flush-timeout-millis: 3000
          close-notify-read-timeout-millis: 0
      routes:
        - id: manager_route
          uri: https://localhost:9090
          predicates:
            - Path=/api/**
        - id: verification_route
          uri: https://localhost:9090
          predicates:
            - Path=/verification/**
        - id: ui_route
          uri: https://localhost
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
