DOCKER_FILE_PATH: /harness/harness-core/pipeline-service/build/container/Dockerfile-pipeline-service-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/pipeline-service/chart
