# Any edit in this file should accompany an increment in version.
name: supportRolesConfiguration
version: 1
roles:
  - identifier: _super_account_viewer
    name: Super Account Viewer
    permissions:
      - core_project_view
      - core_organization_view
      - core_account_view
      - core_secret_view
      - core_connector_view
      - core_delegate_view
      - core_delegateconfiguration_view
      - core_pipeline_view
      - core_service_view
      - core_environment_view
      - core_audit_view
      - core_usergroup_view
      - core_user_view
      - core_role_view
      - core_resourcegroup_view
      - core_license_view
      - core_serviceaccount_view
      - core_authsetting_view
      - core_dashboards_view
      - ff_featureflag_view
      - ff_targetgroup_view
      - ff_target_view
      - ff_environment_apiKeyView
      - ff_environment_view
