mongo:
  uri: mongodb://localhost:27017/idp-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  socketTimeout: 360000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  transactionsEnabled: false
  aliasDBName: idp-harness
  traceMode: DISABLED
  maxOperationTimeInMillis: 300000

server:
  applicationConnectors:
    - type: http
      port: 12003
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: http
      port: 12004
  requestLog:
    appenders: []
  maxThreads: 1024

eventsFramework:
  redis:
    sentinel: false
    masterName: "test"
    redisUrl: "redis://localhost:6379"
    sentinelUrls:
      - "redis://redis1:26379"
      - "redis://redis2:26379"
      - "redis://redis3:26379"
    envNamespace: ""
    readMode: MASTER
    nettyThreads: 16
    useScriptCache: true
    userName: ""
    password: ""
    sslConfig:
      enabled: false
      CATrustStorePath: "/tmp/ca_trust_store"
      CATrustStorePassword: ""

logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false

logStreamingServiceConfig:
  baseUrl: http://localhost:8079
  serviceToken: token

ngManagerServiceHttpClientConfig:
  baseUrl: http://localhost:7457/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

backstageHttpClientConfig:
  baseUrl: http://localhost:7007/api/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

ngManagerServiceSecret: ""
backstageServiceSecret: ""
idpServiceSecret: ""
jwtAuthSecret: ""
jwtIdentityServiceSecret: ""

onboardingModuleConfig:
  tmpPathForCatalogInfoYamlStore: /tmp
  catalogInfoLocationDefaultPath: /.harness-idp-entities
  backstageLocationEntityAllHarnessEntitiesName: "all-harness-entities"
  backstageLocationEntityAllHarnessEntitiesDesc: "Collection of all harness entities - organizations, projects, services and sample entities"
  sampleEntities:
    - https://github.com/harness/harness-core/blob/IDP-Software-Catalog/idp-service/.sample-catalog-entities/one.yaml
    - https://github.com/harness/harness-core/blob/IDP-Software-Catalog/idp-service/.sample-catalog-entities/two.yaml
    - https://github.com/harness/harness-core/blob/IDP-Software-Catalog/idp-service/.sample-catalog-entities/three.yaml
    - https://github.com/harness/harness-core/blob/IDP-Software-Catalog/idp-service/.sample-catalog-entities/four.yaml
    - https://github.com/harness/harness-core/blob/IDP-Software-Catalog/idp-service/.sample-catalog-entities/five.yaml

accessControlClient:
  enableAccessControl: false
  accessControlServiceConfig:
    baseUrl: http://localhost:9006/api/
    connectTimeOutSeconds: 15
    readTimeOutSeconds: 15
  accessControlServiceSecret: ""

backstageSaToken: ""
backstageSaCaCrt: ""
backstageMasterUrl: ""

provisionModuleConfig:
  triggerPipelineUrl: ""