managerUrl: https://localhost:9090/api/
server:
  applicationConnectors:
    - type: https
      port: 6060
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
    - type: http
      port: 6457
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: https
      port: 6061
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
  requestLog:
    appenders: []

logging:
  level: INFO
  loggers:
    com.novemberain.quartz.mongodb: WARN
    org.quartz.plugins: WARN
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    # the following is to suppress "Error retrieving job for trigger XYZ, setting trigger state to ERROR."
    # TODO: remove this suppression when the mentioned issue is resolved
    com.novemberain.quartz.mongodb.TriggerRunner: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %blue(%X{executionId}) %cyan(%logger) - %msg %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false

mongo:
  uri: mongodb://localhost:27017/cvng
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

secretManagerClient:
  baseUrl: http://localhost:7457
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

nextGen:
  managerServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
  ngManagerUrl: http://localhost:7457

dataStorageMode: MONGO
