{{- if .Values.global.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "template-service.name" . }}
  annotations:
    {{- if .Values.global.ingress.objects.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.global.ingress.objects.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    {{- range .Values.global.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "template-service.name" $ }}
                port:
                  number: {{ $.Values.service.port }}
            path: /template(/|$)(.*)
            pathType: ImplementationSpecific
    {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.global.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: template-service-smp-v1-apis
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.global.ingress.objects.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.global.ingress.objects.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
spec:
  ingressClassName: {{ .Values.global.ingress.className | quote }}
  rules:
    {{- range .Values.global.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              service:
                name: template-service
                port:
                  number: {{ $.Values.service.port }}
            path: /(v1/templates.*)
            pathType: ImplementationSpecific
          - backend:
              service:
                name: template-service
                port:
                  number: {{ $.Values.service.port }}
            path: /(v1/orgs/.+/templates.*)
            pathType: ImplementationSpecific
          - backend:
              service:
                name: template-service
                port:
                  number: {{ $.Values.service.port }}
            path: /(v1/orgs/.+/projects/.+/templates.*)
            pathType: ImplementationSpecific
    {{- end }}
  {{- if .Values.global.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range .Values.global.ingress.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.global.ingress.tls.secretName }}
  {{- end }}
{{- end }}
