accountId: kmpySmUISimoRrJL6NL73w
accountSecret: 2f6b0988b6fb3370073c3d0505baee59
managerUrl: https://localhost:9090/api/
heartbeatIntervalMs: 60000
localDiskPath: /tmp
doUpgrade: false
pollForTasks: false
description: description here
