roles:
    - identifier: _project_admin
      name: Project Admin
      description: Administrate an existing project.
      permissions:
        - core_project_view
        - core_project_edit
        - core_project_delete
        - core_secret_view
        - core_secret_edit
        - core_secret_delete
        - core_connector_create
        - core_connector_view
        - core_connector_edit
        - core_connector_delete
        - core_connector_runtimeAccess
        - core_pipeline_view
        - core_pipeline_edit
        - core_pipeline_delete
        - core_pipeline_execute
        - core_service_view
        - core_service_edit
        - core_service_delete
        - core_service_runtimeAccess
        - core_environment_view
        - core_environment_edit
        - core_environment_delete
        - core_environment_runtimeAccess
      allowedScopeLevels:
        - project
      managed: true
    - identifier: _project_viewer
      name: Project Viewer
      description: View a project
      permissions:
        - core_project_view
        - core_secret_view
        - core_connector_view
        - core_pipeline_view
        - core_service_view
        - core_environment_view
      allowedScopeLevels:
        - project
      managed: true
    - identifier: _organization_admin
      name: Organization Admin
      description: Administer an existing organizationn
      permissions:
        - core_organization_view
        - core_organization_edit
        - core_organization_delete
        - core_project_view
        - core_project_create
        - core_secret_delete
        - core_secret_view
        - core_secret_edit
        - core_connector_create
        - core_connector_view
        - core_connector_edit
        - core_connector_delete
        - core_connector_runtimeAccess
        - core_service_view
        - core_service_edit
        - core_service_delete
        - core_service_runtimeAccess
        - core_environment_view
        - core_environment_edit
        - core_environment_delete
        - core_environment_runtimeAccess
      allowedScopeLevels:
        - organization
      managed: true
    - identifier: _organization_viewer
      name: Organization Viewer
      description: View an organization
      permissions:
        - core_organization_view
        - core_project_view
        - core_project_create
        - core_secret_view
        - core_connector_view
        - core_service_view
        - core_environment_view
      allowedScopeLevels:
        - organization
      managed: true
    - identifier: _account_admin
      name: Account Admin
      description: Administer an account
      permissions:
        - core_organization_view
        - core_organization_create
        - core_secret_delete
        - core_secret_view
        - core_secret_edit
        - core_connector_create
        - core_connector_view
        - core_connector_edit
        - core_connector_delete
        - core_connector_runtimeAccess
        - core_service_view
        - core_service_edit
        - core_service_delete
        - core_service_runtimeAccess
        - core_environment_view
        - core_environment_edit
        - core_environment_delete
        - core_environment_runtimeAccess
      allowedScopeLevels:
        - account
      managed: true
    - identifier: _account_viewer
      name: Account Viewer
      description: View an account
      permissions:
        - core_organization_view
        - core_secret_view
        - core_connector_view
        - core_service_view
        - core_environment_view
      allowedScopeLevels:
        - account
      managed: true
    - identifier: _pipeline_executor
      name: Pipeline Executor
      description: Execute a pipeline
      permissions:
        - core_secret_view
        - core_connector_view
        - core_connector_runtimeAccess
        - core_pipeline_view
        - core_pipeline_execute
        - core_service_view
        - core_service_runtimeAccess
        - core_environment_view
        - core_environment_runtimeAccess
      allowedScopeLevels:
        - project
      managed: true