# Any edit in this file should accompany an increment in version.
name: supportRolesConfiguration
version: 20
roles:
  - identifier: _super_account_viewer
    name: Super Account Viewer
    permissions:
      - core_project_view
      - core_organization_view
      - core_account_view
      - core_secret_view
      - core_connector_view
      - core_delegate_view
      - core_delegateconfiguration_view
      - core_pipeline_view
      - core_service_view
      - core_environment_view
      - core_environmentgroup_view
      - core_audit_view
      - core_usergroup_view
      - core_user_view
      - core_role_view
      - core_resourcegroup_view
      - core_license_view
      - core_serviceaccount_view
      - core_serviceaccount_list
      - core_smtp_view
      - core_authsetting_view
      - core_dashboards_view
      - core_streamingDestination_view
      - ff_featureflag_view
      - ff_targetgroup_view
      - ff_target_view
      - ff_environment_apiKeyView
      - ff_environment_view
      - core_template_view
      - core_governancePolicy_view
      - core_governancePolicySets_view
      - chaos_chaoshub_view
      - chaos_chaosinfrastructure_view
      - chaos_chaosexperiment_view
      - chaos_chaosgameday_view
      - chi_monitoredservice_view
      - chi_slo_view
      - chi_downtime_view
      - gitops_agent_view
      - gitops_application_view
      - gitops_repository_view
      - gitops_cluster_view
      - gitops_gpgkey_view
      - gitops_cert_view
      - sto_issue_view
      - sto_scan_view
      - sto_testtarget_view
      - sto_exemption_view
      - sto_ticket_view
      - ccm_overview_view
      - ccm_perspective_view
      - ccm_budget_view
      - ccm_costCategory_view
      - ccm_autoStoppingRule_view
      - ccm_loadBalancer_view
      - ccm_folder_view
      - ccm_currencyPreference_view
      - core_variable_view
      - core_setting_view
      - ccm_cloudAssetGovernanceEnforcement_view
      - ccm_cloudAssetGovernanceRuleSet_view
      - ccm_cloudAssetGovernanceRule_view
      - core_file_view
