DOCKER_FILE_PATH: /harness/harness-core/template-service/build/container/Dockerfile-template-service-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/template-service/chart

