BUILD_SCRIPT_PATH: platform-service/build/feature_build.sh
DOCKER_FILE_PATH: /harness/harness-core/dist/platform-service/Dockerfile-cie-jdk
CONTEXT_PATH: /harness/harness-core/dist/platform-service
ARTIFACT_REPO: harness/feature-platform-service-openjdk-8u242
HELM_CHART_SOURCE_DIRECTORY: harness-core/platform-service/chart
HELM_REPO_NAME: us-west1-docker.pkg.dev/platform-205701/harness-helm-artifacts
BUILD_STEP_RESOURCE_CPU: 1000m
BUILD_STEP_RESOURCE_MEMORY: 3Gi