apiVersion: v1
kind: Secret
metadata:
  name: nextgen-ce
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextgen-ce.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- include "nextgen-ce.generateSecrets" . }}
---
{{- if not .Values.workloadIdentity.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ceng-secret-mount
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nextgen-ce.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations: {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- include "nextgen-ce.generateMountSecrets" . }}
{{- end }}