server:
  applicationConnectors:
    - type: http
      port: 3458
      maxRequestHeaderSize: 100KiB
  requestLog:
    appenders:
      - type: console
        target: STDOUT
        threshold: TRACE
      - type: file
        threshold: TRACE
        currentLogFilename: access.log
        archive: true
        archivedFileCount: 14
        archivedLogFilenamePattern: access.%d.log.gz
  maxThreads: 1024

logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false
    - type: file
      threshold: TRACE
      currentLogFilename: delegate-service.log
      archive: true
      archivedFileCount: 15
      maxFileSize: 150MB
      archivedLogFilenamePattern: delegate-service.%d.%i.log
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"

commonPoolConfig:
  corePoolSize: ${COMMON_POOL_CORE_SIZE:-20}
  maxPoolSize: ${COMMON_POOL_MAX_SIZE:-1000}
  idleTime: ${COMMON_POOL_IDLE_TIME:-500}
  timeUnit: ${COMMON_POOL_IDLE_TIME_TIME_UNIT:-MILLISECONDS}