#Any edit in this file should accompany an increment in version.
name : settingsConfiguration
version : 26
settings :
  - identifier: mandate_webhook_secrets_for_github_triggers
    name: Mandate Webhook Secrets for Github Triggers
    category: PMS
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: disable_harness_built_in_secret_manager
    name: Disable Harness Built-In Secret Manager
    category : CONNECTORS
    defaultValue: false
    valueType : BOOLEAN
    allowedScopes :
      - ACCOUNT
  - identifier: mandate_custom_webhook_authorization
    name: Mandate Authorization for Custom Webhook Triggers
    category: PMS
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: scim_jwt_token_key_field
    name: SCIM JWT token Key field
    category: SCIM
    groupIdentifier: scim_jwt_token_configuration_g1
    valueType: STRING
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
  - identifier: scim_jwt_token_value_field
    name: SCIM JWT token value to be matched for Key field
    category: SCIM
    groupIdentifier: scim_jwt_token_configuration_g1
    valueType: STRING
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
  - identifier: scim_jwt_token_jwks_keys_url
    name: SCIM JWT token jwks keys public URL
    category: SCIM
    groupIdentifier: scim_jwt_token_configuration_g1
    valueType: STRING
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
  - identifier: scim_jwt_token_service_account_id
    name: SCIM JWT token mapped Service Account identifier
    category: SCIM
    groupIdentifier: scim_jwt_token_configuration_g1
    valueType: STRING
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
  - identifier: enable_git_commands
    name: Use Git client for commits
    category: GIT_EXPERIENCE
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
  - identifier: allow_different_repo_for_pipeline_and_input_sets
    name: Allow different repo for Pipeline and InputSets
    category: GIT_EXPERIENCE
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: false
    allowedScopes:
        - ACCOUNT
  - identifier: enable_force_delete
    name: Enable Force Delete of Harness Resources
    category: CORE
    defaultValue: false
    valueType: BOOLEAN
    allowedScopes:
      - ACCOUNT
  - identifier: pipeline_timeout
    name: Pipeline Timeout
    category: PMS
    defaultValue: 1h
    valueType: STRING
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
    allowedPlans:
      FREE:
        defaultValue: 1h
        editable: true
      TEAM:
        defaultValue: 24h
        editable: true
      ENTERPRISE:
        defaultValue: 24h
        editable: true
  - identifier: stage_timeout
    name: Stage Timeout
    category: PMS
    defaultValue: 30m
    valueType: STRING
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
    allowedPlans:
      FREE:
        defaultValue: 30m
        editable: true
      TEAM:
        defaultValue: 24h
        editable: true
      ENTERPRISE:
        defaultValue: 24h
        editable: true
  - identifier: step_timeout
    name: Step Timeout
    category: PMS
    defaultValue: 30m
    valueType: STRING
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
    allowedPlans:
      FREE:
        defaultValue: 30m
        editable: true
      TEAM:
        defaultValue: 10h
        editable: true
      ENTERPRISE:
        defaultValue: 52w
        editable: true
  - identifier: concurrent_active_pipeline_executions
    name: Concurrent Active Pipeline Executions
    category: PMS
    defaultValue: 2
    valueType: NUMBER
    allowedScopes:
      - ACCOUNT
    allowedPlans:
      FREE:
        defaultValue: 2
        editable: false
      TEAM:
# 500 for now.Will make it 200 once the previous execution entries are cleared.
        defaultValue: 500
        editable: false
      ENTERPRISE:
        defaultValue: 500
        editable: true
  - identifier: enable_node_execution_audit_events
    name: Enable Node Execution Audit Events
    category: PMS
    groupIdentifier: pms_execution_settings
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
  - identifier: allow_user_to_mark_step_as_failed_explicitly
    name: Allow user to mark the step as failed explicitly
    category: PMS
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: false
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: default_connector_for_git_experience
    name: Default Connector For Git Experience with Entities- Pipelines/InputSets/Templates
    category: GIT_EXPERIENCE
    defaultValue:
    valueType: String
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: enforce_git_experience
    name: Enforce Git Experience For Entities- Pipelines/InputSets/Templates
    category: GIT_EXPERIENCE
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: default_store_type_for_entities
    name: Default Store Type For Entities- Pipelines/InputSets/Templates
    category: GIT_EXPERIENCE
    defaultValue: INLINE
    valueType: STRING
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
    allowedValues:
      - INLINE
      - REMOTE
  - identifier: default_repo_for_git_experience
    name: Default Repo For Git Experience with Entities- Pipelines/InputSets/Templates
    category: GIT_EXPERIENCE
    defaultValue:
    valueType: String
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: enable_matrix_label_by_name
    name: Enable Matrix Labels By Name
    category: PMS
    groupIdentifier: pms_execution_settings
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: false
    allowedScopes:
      - PROJECT
      - ACCOUNT
      - ORGANIZATION
  - identifier: default_image_pull_policy_for_add_on_container
    name: Default Image Pull Policy For Add On Container
    category: PMS
    groupIdentifier: pms_execution_settings
    defaultValue: Always
    valueType: STRING
    allowOverrides: true
    allowedScopes:
      - PROJECT
      - ACCOUNT
      - ORGANIZATION
    allowedValues:
      - Always
      - IfNotPresent
      - Never
  - identifier: show_anomalies
    name: Show Anomalies
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: true
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
  - identifier: show_others
    name: Show Others
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
  - identifier: show_unallocated_cluster_cost
    name: Show Unallocated cost in Clusters
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
  - identifier: include_aws_discounts
    name: AWS Only - Include Discounts
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: true
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
  - identifier: include_aws_credit
    name: AWS only - Include Credit
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: true
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
  - identifier: include_aws_refunds
    name: AWS only - Include Refunds
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: true
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
  - identifier: include_aws_taxes
    name: AWS only - Include Taxes
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: true
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
  - identifier: show_aws_cost_as
    name: AWS only - Show costs as
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: Unblended
    valueType: STRING
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
    allowedValues:
      - Amortised
      - Net-amortised
      - Unblended
      - Blended
      - Effective
  - identifier: include_gcp_discounts
    name: GCP only - Include Discounts
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: true
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
  - identifier: include_gcp_taxes
    name: GCP only - Include Taxes
    category: CE
    groupIdentifier: perspective_preferences
    defaultValue: true
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
  - identifier: service_override_v2
    name: Service Override V2 Enabled
    category: CD
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: email_to_non_harness_users
    name: Enable Emails to be sent to non-Harness Users
    category: CD
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: enable_expression_engine_v2
    name: Enable Json Support for expressions
    category: PMS
    groupIdentifier: pms_execution_settings
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - PROJECT
      - ACCOUNT
      - ORGANIZATION
  - identifier: export_service_variables_as_env_variables
    name: Export service variables as ENV variables in shell script
    category: PMS
    defaultValue: false
    valueType: BOOLEAN
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT
  - identifier: git_experience_repo_allowlist
    name: Git Experience Repo Allowlist
    category: GIT_EXPERIENCE
    defaultValue:
    valueType: String
    allowOverrides: true
    allowedScopes:
      - ACCOUNT
      - ORGANIZATION
      - PROJECT