server:
  applicationConnectors:
    - type: h2
      port: 9090
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: selfsigned
      validateCerts: false
    - type: http
      port: 3457
  adminConnectors:
    - type: h2
      port: 9091
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: selfsigned
      validateCerts: false

logging:
  appenders:
    - type: console
      threshold: INFO
      target: stdout
    - type: rsyslog-tcp-ssl
      threshold: INFO
      host: logs5.papertrailapp.com
      port: 13747
      programName: manager-saas

mongo:
  host: localhost
  port: 27017
  db: wings

metrics:
  reporters:
  - type: graphite
    host: carbon.hostedgraphite.com
    port: 2003
    prefix: b7eb9d0f-415f-4691-aff3-8228b31277b1

portal:
  url: https://localhost:8000
  allowedDomains: wings.software
  companyName: Wings Software
  authTokenExpiryInMillis: 86400000
