server:
  applicationConnectors:
    - type: h2
      port: 9090
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
      maxRequestHeaderSize: 100KiB
    - type: http
      port: 3457
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: h2
      port: 9091
      keyStorePath: keystore.jks
      keyStorePassword: password
      trustStorePath: ${JAVA_HOME}/jre/lib/security/cacerts
      certAlias: localhost
      validateCerts: false
  requestLog:
    appenders:
      - type: rest-log
        name: rest-accesslogs-appender
        threshold: TRACE
        key: 9a3e6eac4dcdbdc41a93ca99100537df
        programName: manager-saas-accesslogs

hazelcast:
  awsConfig:
    enabled: false
    accessKey: ACCESS_KEY
    secretKey: SECRET_KEY
    region: us-east-1
    securityGroupName: wingsmachine
    tagKey: type
    tagValue: sznodes
  tcpIpConfig:
    enabled: false
    members:
      - 127.0.0.1
    requiredMember: 127.0.0.1

smtp:
  type: SMTP
  host: smtp.gmail.com
  port: 465
  fromAddress: support@harness.io
  useSSL: true
  username: support@harness.io
  password: "H@rness@987"

logging:
  level: INFO
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %n"
    - type: rest-log
      threshold: TRACE
      logFormat: "%green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %n"
      key: 9a3e6eac4dcdbdc41a93ca99100537df
      programName: manager-saas

mongo:
  uri: mongodb://localhost:27017/harness

metrics:
  reporters:
  - type: graphite
    host: carbon.hostedgraphite.com
    port: 2003
    prefix: server

delegateMetadataUrl: http://wingsdelegates.s3-website-us-east-1.amazonaws.com/delegateci.txt

portal:
  url: https://localhost:8000
  allowedDomains: harness.io, wings.software
  allowedOrigins: https://localhost:8000
  companyName: Harness Inc
  authTokenExpiryInMillis: 86400000
  jwtPasswordSecret: a8SGF1CQMHN6pnCJgz32kLn1tebrXnw6MtWto8xI
  jwtExternalServiceSecret: nhUmut2NMcUnsR01OgOz0e51MZ51AqUwrOATJ3fJ

awsEcsAMIByRegion:
  us-east-1: ami-b2df2ca4
  us-east-2: ami-832b0ee6
  us-west-1: ami-dd104dbd
  us-west-2: ami-022b9262
  eu-west-1: ami-a7f2acc1
  eu-west-2: ami-3fb6bc5b
  eu-central-1: ami-ec2be583
  ap-northeast-1: ami-c393d6a4
  ap-southeast-1: ami-a88530cb
  ap-southeast-2: ami-8af8ffe9
  ca-central-1: ami-ead5688e

awsRegionIdToName:
  us-east-1: US East (N. Virginia)
  us-east-2: US East (Ohio)
  us-west-1: US West (N. California)
  us-west-2: US West (Oregon)
  eu-west-1: EU (Ireland)
  eu-west-2: EU (London)
  eu-central-1: EU (Frankfurt)
  ap-northeast-1: Asia Pacific (Tokyo)
  ap-northeast-2: Asia Pacific (Seoul)
  ap-southeast-1: Asia Pacific (Singapore)
  ap-southeast-2: Asia Pacific (Sydney)
  ca-central-1: Canada (Central)
  ap-south-1: Asia Pacific (Mumbai)
  sa-east-1: South America (SÃ£o Paulo)
  us-gov-west-1: GovCloud
  cn-north-1: China North (Beijing)

awsInstanceTypes:
  - t2.nano
  - t2.micro
  - t2.small
  - t2.medium
  - t2.large
  - m3.medium
  - m3.large
  - m3.xlarge
  - m3.2xlarge
  - m4.large
  - m4.xlarge
  - m4.2xlarge
  - m4.4xlarge
  - m4.10xlarge
  - c4.large
  - c4.xlarge
  - c4.2xlarge
  - c4.4xlarge
  - c4.8xlarge
  - c3.large
  - c3.xlarge
  - c3.2xlarge
  - c3.4xlarge
  - c3.8xlarge
  - r3.large
  - r3.xlarge
  - r3.2xlarge
  - r3.4xlarge
  - r3.8xlarge
  - g2.2xlarge
  - g2.8xlarge
  - i2.xlarge
  - i2.2xlarge
  - i2.4xlarge
  - i2.8xlarge
  - d2.xlarge
  - d2.2xlarge
  - d2.4xlarge
  - d2.8xlarge
