logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"

mongo:
  uri: mongodb://localhost:27017/pms-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

grpcServerConfig:
  connectors:
    - port: 12011

grpcClientConfigs:
  cd:
    target: localhost:12101
    authority: localhost
  cv:
    target: localhost:12201
    authority: localhost

allowedOrigins:
  - "*"
