logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"

server:
  applicationConnectors:
    - type: http
      port: 12001
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: http
      port: 12002
  requestLog:
    appenders: []
  maxThreads: 1024

mongo:
  uri: mongodb://localhost:27017/pms-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO

grpcServerConfig:
  connectors:
    - port: 12011
      secure: true
      keyFilePath: 800-pipeline-service/key.pem
      certFilePath: 800-pipeline-service/cert.pem
    - port: 12012

grpcClientConfigs:
  cd:
    target: localhost:12101
    authority: localhost
  cv:
    target: localhost:12201
    authority: localhost
  ci:
    target: localhost:12301
    authority: localhost

ciManagerClientConfig:
  baseUrl: http://localhost:4457/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15
ciManagerServiceSecret: "IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM"


managerTarget: localhost:9880
managerAuthority: localhost
managerServiceSecret: "IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM"

ngManagerServiceHttpClientConfig:
  baseUrl: http://localhost:7457/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15
ngManagerServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM

allowedOrigins:
  - "*"

scmConnectionConfig:
  url: localhost:8091
