logging:
  level: INFO
  loggers:
    org.glassfish.jersey: WARN
    allbegray.slack: WARN
    org.glassfish.jersey.server.ServerRuntime.Responder: "OFF"
  appenders:
    - type: console
      threshold: TRACE
      target: STDOUT
      logFormat: "%date{ISO8601} %green([%thread]) %highlight(%-5level) %cyan(%logger) - %msg %yellow(%replace(%mdc){'(.+)', '[$1]'}) %n"
    - type: gke-console
      threshold: TRACE
      target: STDOUT
      stackdriverLogEnabled: false

server:
  applicationConnectors:
    - type: http
      port: 12001
      maxRequestHeaderSize: 100KiB
  adminConnectors:
    - type: http
      port: 12002
  requestLog:
    appenders: []
  maxThreads: 1024

mongo:
  uri: mongodb://localhost:27017/pms-harness
  connectTimeout: 30000
  serverSelectionTimeout: 90000
  maxConnectionIdleTime: 600000
  connectionsPerHost: 300
  indexManagerMode: AUTO
  transactionsEnabled: false
  aliasDBName:  pms-harness

grpcServerConfig:
  connectors:
    - port: 12011
      secure: true
      keyFilePath: 800-pipeline-service/key.pem
      certFilePath: 800-pipeline-service/cert.pem
    - port: 12012

grpcClientConfigs:
  cd:
    target: localhost:12101
    authority: localhost
  cv:
    target: localhost:12401
    authority: localhost
  ci:
    target: localhost:12301
    authority: localhost

yamlSchemaClientConfig:
  yamlSchemaHttpClientMap:
    ci:
      serviceHttpClientConfig:
        baseUrl: http://localhost:4457/
        connectTimeOutSeconds: 15
        readTimeOutSeconds: 15
      secret: "IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM"
    cd:
      serviceHttpClientConfig:
        baseUrl: http://localhost:7457/
        connectTimeOutSeconds: 15
        readTimeOutSeconds: 15
      secret: "IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM"


managerTarget: localhost:9880
managerAuthority: localhost

eventsFramework:
  redis:
    sentinel: false
    masterName: "test"
    redisUrl: "redis://localhost:6379"
    sentinelUrls:
      - "redis://redis1:26379"
      - "redis://redis2:26379"
      - "redis://redis3:26379"
    envNamespace: ""
    readMode: MASTER
    nettyThreads: 16
    useScriptCache: true
    userName: ""
    password: ""
    sslConfig:
      enabled: false
      CATrustStorePath: "/tmp/ca_trust_store"
      CATrustStorePassword: ""

managerClientConfig:
  baseUrl: http://localhost:3457/api/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15
managerServiceSecret: "IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM"

notificationClient:
  messageBroker:
    type: MONGO
    uri: mongodb://localhost:27017/notification
    connectTimeout: 30000
    serverSelectionTimeout: 90000
    maxConnectionIdleTime: 600000
    connectionsPerHost: 300
  httpClient:
    baseUrl: http://localhost:9005/api/
    connectTimeOutSeconds: 15
    readTimeOutSeconds: 15
  secrets:
    notificationClientSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM

ngManagerServiceHttpClientConfig:
  baseUrl: http://localhost:7457/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15
ngManagerServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM
jwtAuthSecret: dOkdsVqdRPPRJG31XU0qY4MPqmBBMk0PTAGIKM6O7TGqhjyxScIdJe80mwh5Yb5zF3KxYBHw6B3Lfzlq
jwtIdentityServiceSecret: HVSKUYqD4e5Rxu12hFDdCJKGM64sxgEynvdDhaOHaTHhwwn0K4Ttr0uoOxSsEVYNrUU=

allowedOrigins:
  - "*"

accessControlClient:
  enableAccessControl: false
  accessControlServiceConfig:
    baseUrl: http://localhost:9006/api/
    connectTimeOutSeconds: 15
    readTimeOutSeconds: 15
  accessControlServiceSecret: IC04LYMBf1lDP5oeY4hupxd4HJhLmN6azUku3xEbeE3SUx5G3ZYzhbiwVtK4i7AmqyU9OZkwB4v8E9qM

pipelineServiceBaseUrl: https://localhost:8181/#
pmsApiBaseUrl: http://localhost:12001/api/

logStreamingServiceConfig:
  baseUrl: http://localhost:8079
  serviceToken: token

iteratorsConfig:
  approvalInstanceIteratorConfig:
    enabled: true
    targetIntervalInSeconds: 60

enableAuth: false

orchestrationStepConfig:
  ffServerBaseUrl: http://127.0.0.1:3000/api/1.0
  ffServerApiKey: secret

shouldDeployWithGitSync: false

gitSdkConfiguration:
  gitSdkGrpcServerConfig:
    connectors:
      - port: 14001
        secure: true
        keyFilePath: key.pem
        certFilePath: cert.pem
      - port: 14002
  gitManagerGrpcClientConfig:
    target: localhost:13001
    authority: localhost
  scmConnectionConfig:
    url: localhost:8091

enableDashboardTimescale: false

timescaledb:
  timescaledbUrl: "jdbc:postgresql://34.83.25.129:5432/harnessdev"
  timescaledbUsername: "harnessappdev"
  timescaledbPassword: "harnessappdev"
  connectTimeout: 10
  socketTimeout: 30
  logUnclosedConnections: false
  loggerLevel: OFF

auditClientConfig:
  baseUrl: http://localhost:9005/api/
  connectTimeOutSeconds: 15
  readTimeOutSeconds: 15

enableAudit: false

useRedisForInterrupts: false
useRedisForOrchestrationEvents: false
useRedisForSdkResponseEvents: false
