name: Go Build
on:
  pull_request:
    branches:
      - master
      - develop

env:
  BUILD_PURPOSE: RELEASE

jobs:
  gobuild:
    if: contains(github.event.pull_request.labels.*.name, 'go') || contains(github.event.pull_request.labels.*.name, 'gojava')
    name: Go Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Building expression service code
        run: |
          touch bazel-credentials.bzl
          touch test-util.bzl
          echo "JFROG_USERNAME=\"foo\"" >> bazel-credentials.bzl
          echo "JFROG_PASSWORD=\"bar\"" >> bazel-credentials.bzl
          echo "DISTRIBUTE_TESTING_WORKER=0" >> test-util.bzl
          echo "DISTRIBUTE_TESTING_WORKERS=1" >> test-util.bzl
          echo "OPTIMIZED_PACKAGE_TESTS=0" >> test-util.bzl
          
          echo "Building golang expression service protobuf using bazel..."
          bazel build //960-expression-service/src/main/proto/... --javacopt=' -XepDisableAllChecks'

      - name: Building commons code
        run: |
          echo "Building golang commons code using bazel..."
          bazel build //commons/...

      - name: Building product code
        run: |
          echo "Building golang product code using bazel..."
          bazel build //product/... --javacopt=' -XepDisableAllChecks'

      - name: Building gopath
        run: |
          echo "Building gopath"
          bazel build :gopath --javacopt=' -XepDisableAllChecks'

      - name: Testing commons
        run: |
          echo "Testing golang commons code using bazel..."
          bazel test --test_output=all //commons/...

      - name: Testing product
        run: |
          echo "Testing golang product code using bazel..."
          bazel test --test_output=all //product/... --javacopt=' -XepDisableAllChecks'

      - name: Coverage
        run: |
          export GOPATH=$(go env GOPATH)
          export PATH=$PATH:$GOPATH/bin
          echo $PATH
          echo $GOPATH
          echo "Adding gocovmerge package... "
          go install github.com/wadey/gocovmerge@latest
          tools/go/generate_coverage.sh func
