name: No-op Tests for Go
on:
  pull_request:
    branches:
      - master

jobs:
  no_op_go:
    if: contains(github.event.pull_request.labels.*.name, 'go')
    name: No-op tests for Go
    runs-on: ubuntu-18.04
    steps:
      - name: Complete ti0
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: runUnitTests0-unittest0
          description: 'Mark ti0 as success'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Complete ti1
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: runUnitTests1-unittest1
          description: 'Mark ti1 as success'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Complete ti2
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: runUnitTests2-unittest2
          description: 'Mark ti2 as success'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Complete ti3
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: runUnitTests3-unittest3
          description: 'Mark ti3 as success'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Complete ti4
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: runUnitTests4-unittest4
          description: 'Mark ti4 as success'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Complete pmd checks
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: runPMDCheck-PMDCheck
          description: 'Mark PMD checks as success'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Complete maven build
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: runMavenBuild-mavenbuild
          description: 'Mark maven build as success'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Complete check-style
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: runCheckstyleCheck-checkstylecheck
          description: 'Mark check-style as success'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}

      - name: Complete aeriform check
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: runAeriformCheck-AeriformCheck
          description: 'Mark aeriform-check as success'
          state: 'success'
          sha: ${{github.event.pull_request.head.sha || github.sha}}