{{- if .Values.global.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: log-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.global.commonLabels }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.virtualService.annotations }}
    {{- include "harnesscommon.tplvalues.render" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.global.commonAnnotations }}
    {{- include "harnesscommon.tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  gateways:
    {{- if .Values.global.istio.gateway.create }}
    - istio-system/public
    {{- else }}
    {{- range .Values.global.istio.virtualService.gateways }}
    - {{ . }}
    {{- end }}
    {{- end }}
  hosts:
    {{- range .Values.global.istio.virtualService.hosts }}
    - {{ . }}
    {{- end }}
  http:
  - name: log-service
    match:
    - uri:
        prefix: /log-service/
    - uri:
        prefix: /log-service
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: log-service
{{ end }}