DOCKER_FILE_PATH: /harness/harness-core/315-sto-manager/build/container/Dockerfile-sto-manager-multistage
CONTEXT_PATH: /harness/harness-core
HELM_CHART_SOURCE_DIRECTORY: harness-core/315-sto-manager/chart
